---
title: "Analisis de arroz"
author: "Dra. Patricia Zavala Villagómez"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
  word_document:
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(siebanxicor)
library(dplyr)
library(plotly)
library(DT)
library(openxlsx)
library(stargazer)

# importamos datos
arroz=read.xlsx("datosarroz.xlsx")
arroz$Fecha=as.Date(arroz$Fecha,origin="1988-12-30")
```

agurparemos toda la informacion en una sola tabla
```{r}

serieTiempoArroz=arroz%>%group_by(Fecha)%>%
summarise(precioMedio=mean(Precio.Frecuente), desvEst=sd(Precio.Frecuente))
```

Ahora hacemos una base de datos panel, para un analisis panel 
```{r}
panelArroz=arroz%>%group_by(Producto,Fecha)%>%
summarise(precioMedio=mean(Precio.Frecuente), desvEst=sd(Precio.Frecuente),
          minimo=min(Precio.Frecuente),maximo=max(Precio.Frecuente))
```
Ahora exportaremos los datos en tabla panel a un archivo de excel:
```{r}
write.xlsx(panelArroz,"panelArroz.xlsx")
```
Filtramos fechas para que presente fechas de datos mas recientes a partir de 27 de mayo del 2024
```{r filtrarfechas}
arrozFiltrado=arroz%>%filter(Fecha>="2024-05-01")

```

```{r grafica}
figura1=plot_ly()

figura1=add_trace(figura1,x=~Fecha,y=~precioMedio,data=serieTiempoArroz,type="scatter",mode="lines",name="Precio maximo arroz")

figura1=add_trace(figura1,x=~Fecha,y=~minimo,data=serieTiempoArroz,type="scatter",mode="lines",name="Precio maximo arroz")

figura1=add_trace(figura1,x=~Fecha,y=~maximo,data=serieTiempoArroz,type="scatter",mode="lines",name="Precio maximo arroz")

figura1=layout(figura1,title="Precio arroz", 
               xaxis=list(title="Fecha",
                     rangeslider=list(type="date")),
               yaxis=list(title="Precio arroz"))
figura1

```

